# Site settings
email: rlhtutoring22@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "RLH Tutoring - Online and face to face tutoring - Early Secondary - A Level"
keywords: "maths, maths tutoring, Gainsborough tutoring, A level maths tutoring, GCSE maths tutoring, online tutoring, tutoring, RLH tutoring, RLH maths tutoring"
skills: "19 years maths teaching experience, first-class degree in Mathematics with European Studies from The University of Sussex (1995), PGCE from Leeds University (2005) alongside my Qualified Teaching Status Certificate gained in 2006"
meta_author: Ward Craig

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
# contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: B1D9B7
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: RLH Maths Tutoring
  location: Gainsborough
  social: Around the Web
  credits: Craig Ward Web Design

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/people/RLH-Maths-Tutoring/100089392861574/

# Postal address (add as many lines as necessary)
#address:
 # - line: 3481 Melrose Place
  #- line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
